out_bitrate: 64k
out_format: mp3 # mp3 aac opus
format: audio-24khz-160kbitrate-mono-mp3 # riff-24khz-16bit-mono-pcm audio-24khz-160kbitrate-mono-mp3
templates:
  - tag: 女1
    name: zh-CN-XiaomoNeural
  - tag: g
    name: zh-CN-XiaomoNeural
    style: gentle
    role: YoungAdultMale
  - tag: 男1
    name: zh-CN-YunxiNeural
    role: Narrator
    style: narration-relaxed
default: g
limit:
  word_count: 300
  ssml_count: 700